spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${MYSQL_PASSWORD}
  #  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: validate  # (1) 스키마 자동 생성
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true      # (2) SQL 쿼리 출력
    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
#  config:
#    domain:
#      s3엔드포인트
jwt:
  key: ${JWT_SECRET_KEY} #secretKey는 환경변수로
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420